source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MGAFoundation_Example', :exclusive => true do
  pod "MGAFoundation", :path => "../"
end

target 'MGAFoundation_Tests', :exclusive => true do
  pod "MGAFoundation", :path => "../"
  pod 'Quick', '~> 0.6.0'
  pod 'Nimble', '2.0.0-rc.3'
  pod 'FBSnapshotTestCase'
end
